name: otorep
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/otorep_logo.png"

flutter_native_splash:
  color: "#1D1D4B"
  image: "lib/splash_logo.png"
  android_12:
    image: "lib/splash_logo.png"
    color: "#1D1D4B"
    icon_background_color: "#1D1D4B"

flutter:
  uses-material-design: true
  assets:
    - lib/otorep_logo.png